export const ApiScopes = new Map();
ApiScopes.set("analytics:read:extensions", "View analytics data for the Twitch Extensions owned by the authenticated account.");
ApiScopes.set("analytics:read:games", "View analytics data for the games owned by the authenticated account.");
ApiScopes.set("bits:read", "View Bits information for a channel.");
ApiScopes.set("channel:edit:commercial", "Run commercials on a channel.");
ApiScopes.set("channel:manage:broadcast", "Manage a channel’s broadcast configuration, including updating channel configuration and managing stream markers and stream tags.");
ApiScopes.set("channel:manage:extensions", "Manage a channel’s Extension configuration, including activating Extensions.");
ApiScopes.set("channel:manage:moderators", "Add or remove the moderator role from users in your channel.");
ApiScopes.set("channel:manage:polls", "Manage a channel’s polls.");
ApiScopes.set("channel:manage:predictions", "Manage of channel’s Channel Points Predictions");
ApiScopes.set("channel:manage:raids", "Manage a channel raiding another channel.");
ApiScopes.set("channel:manage:redemptions", "Manage Channel Points custom rewards and their redemptions on a channel.");
ApiScopes.set("channel:manage:schedule", "Manage a channel’s stream schedule.");
ApiScopes.set("channel:manage:videos", "Manage a channel’s videos, including deleting videos.");
ApiScopes.set("channel:manage:vips", "Add or remove the VIP role from users in your channel.");
ApiScopes.set("channel:read:charity", "Read charity campaign details and user donations on your channel.");
ApiScopes.set("channel:read:editors", "View a list of users with the editor role for a channel.");
ApiScopes.set("channel:read:goals", "View Creator Goals for a channel.");
ApiScopes.set("channel:read:hype_train", "View Hype Train information for a channel.");
ApiScopes.set("channel:read:polls", "View a channel’s polls.");
ApiScopes.set("channel:read:predictions", "View a channel’s Channel Points Predictions.");
ApiScopes.set("channel:read:redemptions", "View Channel Points custom rewards and their redemptions on a channel.");
ApiScopes.set("channel:read:stream_key", "View an authorized user’s stream key.");
ApiScopes.set("channel:read:subscriptions", "View a list of all subscribers to a channel and check if a user is subscribed to a channel.");
ApiScopes.set("channel:read:vips", "Read the list of VIPs in your channel.");
ApiScopes.set("clips:edit", "Manage Clips for a channel.");
ApiScopes.set("moderation:read", "View a channel’s moderation data including Moderators, Bans, Timeouts, and Automod settings.");
ApiScopes.set("moderator:manage:announcements", "Send announcements in channels where you have the moderator role.");
ApiScopes.set("moderator:manage:automod", "Manage messages held for review by AutoMod in channels where you are a moderator.");
ApiScopes.set("moderator:manage:automod_settings", "Manage a broadcaster’s AutoMod settings.");
ApiScopes.set("moderator:manage:banned_users", "Ban and unban users.");
ApiScopes.set("moderator:manage:blocked_terms", "Manage a broadcaster’s list of blocked terms.");
ApiScopes.set("moderator:manage:chat_messages", "Delete chat messages in channels where you have the moderator role");
ApiScopes.set("moderator:manage:chat_settings", "Manage a broadcaster’s chat room settings.");
ApiScopes.set("moderator:manage:shield_mode", "Manage a broadcaster’s Shield Mode status.");
ApiScopes.set("moderator:manage:shoutouts", "Do shoutouts");
ApiScopes.set("moderator:read:automod_settings", "View a broadcaster’s AutoMod settings.");
ApiScopes.set("moderator:read:blocked_terms", "View a broadcaster’s list of blocked terms.");
ApiScopes.set("moderator:read:chat_settings", "View a broadcaster’s chat room settings.");
ApiScopes.set("moderator:read:chatters", "View the chatters in a broadcaster’s chat room.");
ApiScopes.set("moderator:read:followers", "View the channel's followers.");
ApiScopes.set("moderator:read:shield_mode", "View a broadcaster’s Shield Mode status.");
ApiScopes.set("user:edit", "Manage a user object.");
ApiScopes.set("user:manage:blocked_users", "Manage the block list of a user.");
ApiScopes.set("user:manage:chat_color", "Update the color used for the user’s name in chat.Update User Chat Color");
ApiScopes.set("user:manage:whispers", "Read whispers that you send and receive, and send whispers on your behalf.");
ApiScopes.set("user:read:blocked_users", "View the block list of a user.");
ApiScopes.set("user:read:broadcast", "View a user’s broadcasting configuration, including Extension configurations.");
ApiScopes.set("user:read:email", "View a user’s email address.");
ApiScopes.set("user:read:follows", "View the list of channels a user follows.");
ApiScopes.set("user:read:subscriptions", "View if an authorized user is subscribed to specific channels.");
